# * © JamesRoll [ ijamesroll.software ] - JamesBukkitElements
# * This product is distributed under the MIT license
# * (https://github.com/ijamesroll/ijamesroll-bukkitelements/LICENSE)
# * * *
# * The author does not bear any responsibility for this development.
# * It is also prohibited to delete this copyright message.
# * * *
# * Author contacts: https://vk.com/ijamesroll, admin@ijamesroll.software, https://t.me/ijamesroll
name: BukkitElements
author: ijamesroll
main: software.ijamesroll.bukkitelements.BukkitElementsLoader
version: 0.1